export const tiers = [
  {
    rank: 0,
    name: "Apprentice",
    points: "0",
    badge: "Wooden shield",
    reward: "Leaderboard access",
    color: "#92400E",
    bgColor: "#78350F",
  },
  {
    rank: 1,
    name: "Scribe",
    points: "25",
    badge: "Bronze scroll",
    reward: "Quick-start guide",
    color: "#CD7F32",
    bgColor: "#92400E",
  },
  {
    rank: 2,
    name: "Builder",
    points: "100",
    badge: "Silver hammer",
    reward: "Free training module + Discord role",
    color: "#C0C0C0",
    bgColor: "#475569",
  },
  {
    rank: 3,
    name: "Architect",
    points: "300",
    badge: "Gold compass",
    reward: "Full training course + early video access",
    color: "#F59E0B",
    bgColor: "#78350F",
  },
  {
    rank: 4,
    name: "Sage",
    points: "750",
    badge: "Emerald eye",
    reward: "Tool license + monthly Q&A access",
    color: "#10B981",
    bgColor: "#064E3B",
  },
  {
    rank: 5,
    name: "Master",
    points: "1,500",
    badge: "Ruby crown",
    reward: "1:1 coaching session + beta content",
    color: "#DC2626",
    bgColor: "#7F1D1D",
  },
  {
    rank: 6,
    name: "Archon",
    points: "3,000",
    badge: "Diamond tower",
    reward: "Annual tool bundle + quarterly mastermind",
    color: "#60A5FA",
    bgColor: "#1E3A5F",
  },
  {
    rank: 7,
    name: "Legend",
    points: "6,000+",
    badge: "Obsidian throne",
    reward: "Co-host videos + all rewards + strategy session",
    color: "#F59E0B",
    bgColor: "#1a1a1a",
  },
] as const;

export const mockLeaderboard = [
  { rank: 1, name: "@codeforge", tier: "Legend", active: "6,420", lifetime: "12,841", streak: 47 },
  { rank: 2, name: "@neuralcrafter", tier: "Archon", active: "4,215", lifetime: "9,830", streak: 32 },
  { rank: 3, name: "@buildwithkai", tier: "Master", active: "2,890", lifetime: "7,214", streak: 28 },
  { rank: 4, name: "@aiarchitect", tier: "Sage", active: "1,245", lifetime: "4,567", streak: 14 },
  { rank: 5, name: "@devscribe", tier: "Architect", active: "487", lifetime: "1,892", streak: 7 },
] as const;

export const leagues = [
  "Bronze League",
  "Silver League",
  "Gold League",
  "Platinum League",
  "Diamond League",
  "Champion League",
] as const;
